### list
GET http://localhost:3000/posts

### query
GET http://localhost:3000/posts?_q=title

### show
GET http://localhost:3000/posts/1

### create
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Hello, world!",
  "content": "This is my first post."
}

### update
PUT http://localhost:3000/posts/1
Content-Type: application/json

{
  "title": "Hello, world!",
  "content": "This is my first post. (updated)"
}

### delete
DELETE http://localhost:3000/posts/1